"""
Mathful Minds — Skills Catalog
All 245 skills organized by domain and subcategory.
"""

DOMAINS = {
    "Number Sense": {
        "icon": "🔢",
        "subcategories": {
            "Integers": [
                {"id": 1, "name": "Represent integers on a number line"},
                {"id": 2, "name": "Opposites and absolute value"},
                {"id": 3, "name": "Compare and order integers"},
                {"id": 4, "name": "Add integers"},
                {"id": 5, "name": "Subtract integers"},
                {"id": 6, "name": "Multiply / divide integers"},
                {"id": 7, "name": "Apply integer operations (multi-step)"},
            ],
            "Rational Numbers": [
                {"id": 8, "name": "Identify rational numbers (terminating vs. repeating)"},
                {"id": 9, "name": "Add rational numbers"},
                {"id": 10, "name": "Subtract rational numbers"},
                {"id": 11, "name": "Multiply rational numbers"},
                {"id": 12, "name": "Divide rational numbers"},
                {"id": 13, "name": "Apply rational number operations"},
                {"id": 14, "name": "Divide multi-digit numbers"},
                {"id": 15, "name": "Compute with multi-digit decimals"},
                {"id": 16, "name": "Divide whole numbers by fractions"},
                {"id": 17, "name": "Divide fractions by fractions"},
                {"id": 18, "name": "Divide with whole and mixed numbers"},
            ],
            "Real Numbers": [
                {"id": 19, "name": "Roots (square roots, cube roots)"},
                {"id": 20, "name": "Classify real numbers (rational vs. irrational)"},
                {"id": 21, "name": "Estimate irrational numbers"},
                {"id": 22, "name": "Compare and order real numbers"},
            ],
        },
    },
    "Ratios & Proportions": {
        "icon": "⚖️",
        "subcategories": {
            "Ratios": [
                {"id": 23, "name": "Understand ratios"},
                {"id": 24, "name": "Tables of equivalent ratios"},
                {"id": 25, "name": "Graphs of equivalent ratios"},
                {"id": 26, "name": "Compare ratio relationships"},
                {"id": 27, "name": "Solve ratio problems"},
                {"id": 28, "name": "Convert customary measurement units"},
            ],
            "Rates & Unit Rates": [
                {"id": 29, "name": "Understand rates and unit rates"},
                {"id": 30, "name": "Solve rate problems"},
                {"id": 31, "name": "Unit rates involving ratios of fractions"},
                {"id": 32, "name": "Dimensional analysis"},
            ],
            "Proportional Relationships": [
                {"id": 33, "name": "Understand proportional relationships"},
                {"id": 34, "name": "Tables of proportional relationships"},
                {"id": 35, "name": "Graphs of proportional relationships"},
                {"id": 36, "name": "Equations of proportional relationships (y = kx)"},
                {"id": 37, "name": "Solve problems involving proportional relationships"},
            ],
            "Percents": [
                {"id": 38, "name": "Understand percents"},
                {"id": 39, "name": "Percents greater than 100% and less than 1%"},
                {"id": 40, "name": "Relate fractions, decimals, and percents"},
                {"id": 41, "name": "Find the percent of a number"},
                {"id": 42, "name": "Estimate the percent of a number"},
                {"id": 43, "name": "Find the whole given a percent"},
                {"id": 44, "name": "Percent of change"},
                {"id": 45, "name": "Tax"},
                {"id": 46, "name": "Tips and markup"},
                {"id": 47, "name": "Discounts"},
                {"id": 48, "name": "Commission and fees"},
                {"id": 49, "name": "Interest (simple)"},
                {"id": 50, "name": "Percent error"},
            ],
            "Proportions": [
                {"id": 51, "name": "Solving proportions"},
            ],
        },
    },
    "Expressions & Equations": {
        "icon": "📐",
        "subcategories": {
            "Expressions": [
                {"id": 52, "name": "Powers and exponents"},
                {"id": 53, "name": "Numerical expressions (order of operations)"},
                {"id": 54, "name": "Write algebraic expressions"},
                {"id": 55, "name": "Evaluate algebraic expressions"},
                {"id": 56, "name": "Factors and multiples (GCF, LCM)"},
                {"id": 57, "name": "Distributive property"},
                {"id": 58, "name": "Equivalent algebraic expressions"},
                {"id": 59, "name": "Properties of real numbers"},
                {"id": 60, "name": "Expressions involving absolute value"},
                {"id": 61, "name": "Simplify algebraic expressions"},
                {"id": 62, "name": "Add linear expressions"},
                {"id": 63, "name": "Subtract linear expressions"},
                {"id": 64, "name": "Factor linear expressions"},
                {"id": 65, "name": "Combine operations with linear expressions"},
            ],
            "One-Step Equations": [
                {"id": 66, "name": "Use substitution to solve one-step equations"},
                {"id": 67, "name": "One-step addition equations"},
                {"id": 68, "name": "One-step subtraction equations"},
                {"id": 69, "name": "One-step multiplication equations"},
                {"id": 70, "name": "One-step division equations"},
                {"id": 71, "name": "Write and solve one-step equations"},
            ],
            "Multi-Step Equations": [
                {"id": 72, "name": "Solve two-step equations: px + q = r"},
                {"id": 73, "name": "Solve two-step equations: p(x + q) = r"},
                {"id": 74, "name": "Write and solve two-step equations"},
                {"id": 75, "name": "Solve equations with variables on each side"},
                {"id": 76, "name": "Solve multi-step equations"},
                {"id": 77, "name": "Write and solve multi-step equations"},
                {"id": 78, "name": "Determine the number of solutions"},
                {"id": 79, "name": "Writing and interpreting equations"},
                {"id": 80, "name": "Solving equations involving absolute value"},
                {"id": 81, "name": "Using formulas / literal equations"},
            ],
            "Inequalities": [
                {"id": 82, "name": "Inequalities (introduction)"},
                {"id": 83, "name": "Solve one-step add/subtract inequalities"},
                {"id": 84, "name": "Solve one-step multiply/divide inequalities (positive)"},
                {"id": 85, "name": "Solve one-step multiply/divide inequalities (negative)"},
                {"id": 86, "name": "Write and solve two-step inequalities"},
                {"id": 87, "name": "Solve multi-step inequalities"},
                {"id": 88, "name": "Solve compound inequalities"},
                {"id": 89, "name": "Solve absolute value inequalities"},
                {"id": 90, "name": "Graph inequalities in two variables"},
            ],
            "Linear Relationships": [
                {"id": 91, "name": "Relationships between two variables"},
                {"id": 92, "name": "Write equations from tables"},
                {"id": 93, "name": "Graphs of relationships"},
                {"id": 94, "name": "Multiple representations"},
                {"id": 95, "name": "Proportional relationships and slope"},
                {"id": 96, "name": "Slope of a line (from graph, from points)"},
                {"id": 97, "name": "Similar triangles and slope"},
                {"id": 98, "name": "Direct variation"},
                {"id": 99, "name": "Slope-intercept form"},
                {"id": 100, "name": "Graph linear equations"},
                {"id": 101, "name": "Standard form to slope-intercept form"},
                {"id": 102, "name": "Writing equations in slope-intercept form"},
                {"id": 103, "name": "Writing equations in standard and point-slope form"},
                {"id": 104, "name": "Rate of change and slope"},
            ],
            "Functions": [
                {"id": 105, "name": "Identify functions (input-output)"},
                {"id": 106, "name": "Function tables (domain and range)"},
                {"id": 107, "name": "Construct linear functions"},
                {"id": 108, "name": "Compare functions"},
                {"id": 109, "name": "Nonlinear functions"},
                {"id": 110, "name": "Qualitative graphs"},
                {"id": 111, "name": "Representing relations"},
                {"id": 112, "name": "Functions (formal definition)"},
                {"id": 113, "name": "Interpreting graphs: linearity and continuity"},
                {"id": 114, "name": "Interpreting graphs: intercepts and symmetry"},
                {"id": 115, "name": "Scatter plots"},
                {"id": 116, "name": "Draw lines of fit"},
                {"id": 117, "name": "Equations for lines of fit"},
            ],
            "Systems": [
                {"id": 118, "name": "Determine number of solutions (systems)"},
                {"id": 119, "name": "Solve systems by graphing"},
                {"id": 120, "name": "Solve systems by substitution"},
                {"id": 121, "name": "Solve systems by elimination"},
                {"id": 122, "name": "Write and solve systems of equations"},
                {"id": 123, "name": "Systems of inequalities"},
            ],
            "Exponents & Polynomials": [
                {"id": 124, "name": "Multiply and divide monomials"},
                {"id": 125, "name": "Powers of monomials"},
                {"id": 126, "name": "Zero and negative exponents"},
                {"id": 127, "name": "Scientific notation"},
                {"id": 128, "name": "Compute with scientific notation"},
                {"id": 129, "name": "Multiplication properties of exponents"},
                {"id": 130, "name": "Division properties of exponents"},
                {"id": 131, "name": "Negative exponents (Algebra 1)"},
                {"id": 132, "name": "Simplifying radical expressions"},
                {"id": 133, "name": "Operations with radical expressions"},
                {"id": 134, "name": "Adding and subtracting polynomials"},
                {"id": 135, "name": "Multiplying a polynomial by a monomial"},
                {"id": 136, "name": "Multiplying polynomials (FOIL / distribution)"},
                {"id": 137, "name": "Special products"},
                {"id": 138, "name": "Factoring using distributive property (GCF)"},
                {"id": 139, "name": "Factoring quadratic trinomials"},
                {"id": 140, "name": "Factoring special products"},
                {"id": 141, "name": "Simplifying rational expressions"},
                {"id": 142, "name": "Solving quadratic equations by factoring"},
                {"id": 143, "name": "Solving quadratic equations using the quadratic formula"},
            ],
        },
    },
    "Geometry": {
        "icon": "📏",
        "subcategories": {
            "Area & Perimeter": [
                {"id": 144, "name": "Area of parallelograms"},
                {"id": 145, "name": "Area of triangles"},
                {"id": 146, "name": "Area of trapezoids"},
                {"id": 147, "name": "Area of regular polygons"},
                {"id": 148, "name": "Polygons on the coordinate plane"},
                {"id": 149, "name": "Volume of rectangular prisms"},
                {"id": 150, "name": "Surface area of rectangular prisms"},
                {"id": 151, "name": "Surface area of triangular prisms"},
                {"id": 152, "name": "Volume of prisms and pyramids"},
                {"id": 153, "name": "Surface area of prisms and pyramids"},
                {"id": 154, "name": "Volume of cylinders"},
                {"id": 155, "name": "Volume of cones"},
                {"id": 156, "name": "Volume of spheres"},
                {"id": 157, "name": "Finding missing dimensions"},
                {"id": 158, "name": "Volume of composite solids"},
                {"id": 159, "name": "Circumference of circles"},
                {"id": 160, "name": "Area of circles"},
                {"id": 161, "name": "Area of composite figures"},
            ],
            "Angles": [
                {"id": 162, "name": "Vertical and adjacent angles"},
                {"id": 163, "name": "Complementary and supplementary angles"},
                {"id": 164, "name": "Parallel lines cut by a transversal"},
                {"id": 165, "name": "Triangles (angle sum, triangle inequality)"},
                {"id": 166, "name": "Angle relationships and triangles"},
            ],
            "Scale & Measurement": [
                {"id": 167, "name": "Scale drawings"},
                {"id": 168, "name": "Three-dimensional figures"},
            ],
            "Pythagorean Theorem": [
                {"id": 169, "name": "The Pythagorean Theorem"},
                {"id": 170, "name": "Converse of the Pythagorean Theorem"},
                {"id": 171, "name": "Distance on the coordinate plane"},
            ],
            "Transformations": [
                {"id": 172, "name": "Translations"},
                {"id": 173, "name": "Reflections"},
                {"id": 174, "name": "Rotations"},
                {"id": 175, "name": "Dilations"},
                {"id": 176, "name": "Sequence of transformations"},
                {"id": 177, "name": "Congruence and transformations"},
                {"id": 178, "name": "Congruence and corresponding parts"},
                {"id": 179, "name": "Similarity and transformations"},
                {"id": 180, "name": "Similarity and corresponding parts"},
                {"id": 181, "name": "Indirect measurement"},
            ],
            "Geometry Foundations": [
                {"id": 182, "name": "Points, lines, and planes"},
                {"id": 183, "name": "Line segments and distance"},
                {"id": 184, "name": "Midpoints and bisectors"},
                {"id": 185, "name": "Angles and congruence"},
                {"id": 186, "name": "Conjectures and counterexamples"},
                {"id": 187, "name": "Conditionals and biconditionals"},
                {"id": 188, "name": "Writing proofs"},
                {"id": 189, "name": "Deductive reasoning"},
                {"id": 190, "name": "Proving segment and angle relationships"},
                {"id": 191, "name": "Parallel lines and transversals (Geometry)"},
                {"id": 192, "name": "Slope and equations of lines (Geometry)"},
                {"id": 193, "name": "Proving lines parallel"},
            ],
            "Triangles & Congruence": [
                {"id": 194, "name": "Congruent triangles (SSS, SAS, ASA, AAS)"},
                {"id": 195, "name": "Proving right triangles congruent"},
                {"id": 196, "name": "Isosceles and equilateral triangles"},
                {"id": 197, "name": "Triangle congruence proofs"},
                {"id": 198, "name": "Angles of polygons"},
                {"id": 199, "name": "Parallelograms (properties and tests)"},
                {"id": 200, "name": "Rectangles, rhombi, squares"},
                {"id": 201, "name": "Trapezoids and kites"},
            ],
            "Similarity & Trigonometry": [
                {"id": 202, "name": "Similar polygons"},
                {"id": 203, "name": "Similar triangles (AA, SSS, SAS similarity)"},
                {"id": 204, "name": "Triangle proportionality"},
                {"id": 205, "name": "Parts of similar triangles"},
                {"id": 206, "name": "Perpendicular bisectors and angle bisectors"},
                {"id": 207, "name": "Medians and altitudes of triangles"},
                {"id": 208, "name": "Inequalities in triangles"},
                {"id": 209, "name": "Geometric mean"},
                {"id": 210, "name": "Pythagorean Theorem and converse (Geometry)"},
                {"id": 211, "name": "Special right triangles (30-60-90, 45-45-90)"},
                {"id": 212, "name": "Trigonometry (sin, cos, tan)"},
                {"id": 213, "name": "Applying trigonometry"},
            ],
            "Circles (Geometry)": [
                {"id": 214, "name": "Circles and circumference (Geometry)"},
                {"id": 215, "name": "Measuring angles and arcs"},
                {"id": 216, "name": "Arcs and chords"},
                {"id": 217, "name": "Inscribed angles"},
                {"id": 218, "name": "Tangents"},
                {"id": 219, "name": "Tangents, secants, and angle measures"},
                {"id": 220, "name": "Areas of quadrilaterals (Geometry)"},
                {"id": 221, "name": "Areas of regular polygons (Geometry)"},
                {"id": 222, "name": "Areas of circles and sectors"},
            ],
        },
    },
    "Statistics & Probability": {
        "icon": "📊",
        "subcategories": {
            "Data & Statistics": [
                {"id": 223, "name": "Statistical questions"},
                {"id": 224, "name": "Dot plots and histograms"},
                {"id": 225, "name": "Measures of center (mean, median, mode)"},
                {"id": 226, "name": "Interquartile range and box plots"},
                {"id": 227, "name": "Mean absolute deviation"},
                {"id": 228, "name": "Outliers"},
                {"id": 229, "name": "Interpret graphical displays"},
                {"id": 230, "name": "Representing data"},
                {"id": 231, "name": "Using data"},
                {"id": 232, "name": "Measures of spread"},
            ],
            "Probability": [
                {"id": 233, "name": "Find likelihoods"},
                {"id": 234, "name": "Relative frequency"},
                {"id": 235, "name": "Theoretical probability"},
                {"id": 236, "name": "Compare probabilities"},
                {"id": 237, "name": "Probability of compound events"},
                {"id": 238, "name": "Fundamental counting principle"},
            ],
            "Sampling & Inference": [
                {"id": 239, "name": "Biased and unbiased samples"},
                {"id": 240, "name": "Make predictions"},
                {"id": 241, "name": "Generate multiple samples"},
                {"id": 242, "name": "Compare two populations"},
                {"id": 243, "name": "Two-way tables"},
                {"id": 244, "name": "Associations in two-way tables"},
            ],
            "Review": [
                {"id": 245, "name": "Solving proportions (Algebra 1)"},
            ],
        },
    },
}


def get_all_skills():
    """Return a flat list of all skills with domain info."""
    skills = []
    for domain_name, domain_data in DOMAINS.items():
        for subcat_name, skill_list in domain_data["subcategories"].items():
            for skill in skill_list:
                skills.append({
                    "id": skill["id"],
                    "name": skill["name"],
                    "domain": domain_name,
                    "subcategory": subcat_name,
                    "icon": domain_data["icon"],
                })
    return skills


def get_skill_by_id(skill_id):
    """Look up a single skill by its ID."""
    for skill in get_all_skills():
        if skill["id"] == skill_id:
            return skill
    return None
